// bibleData.ts

export const OldTestament = {
  Genesis: { title: 'Бытие', chapters: 50, bookId: 1 },
  Exodus: { title: 'Исход', chapters: 40, bookId: 2 },
  Leviticus: { title: 'Левит', chapters: 27, bookId: 3 },
  Numbers: { title: 'Числа', chapters: 36, bookId: 4 },
  Deuteronomy: { title: 'Второзаконие', chapters: 34, bookId: 5 },
  Joshua: { title: 'Иисус Навин', chapters: 24, bookId: 6 },
  Judges: { title: 'Судей', chapters: 21, bookId: 7 },
  Ruth: { title: 'Руфь', chapters: 4, bookId: 8 },
  '1 Samuel': { title: '1 Царств', chapters: 31, bookId: 9 },
  '2 Samuel': { title: '2 Царств', chapters: 24, bookId: 10 },
  '1 Kings': { title: '3 Царств', chapters: 22, bookId: 11 },
  '2 Kings': { title: '4 Царств', chapters: 25, bookId: 12 },
  '1 Chronicles': { title: '1 Паралипоменон', chapters: 29, bookId: 13 },
  '2 Chronicles': { title: '2 Паралипоменон', chapters: 36, bookId: 14 },
  Ezra: { title: 'Ездра', chapters: 10, bookId: 15 },
  Nehemiah: { title: 'Неемия', chapters: 13, bookId: 16 },
  Esther: { title: 'Есфирь', chapters: 10, bookId: 17 },
  Job: { title: 'Иов', chapters: 42, bookId: 18 },
  Psalms: { title: 'Псалтирь', chapters: 150, bookId: 19 },
  Proverbs: { title: 'Притчи', chapters: 31, bookId: 20 },
  Ecclesiastes: { title: 'Екклесиаст', chapters: 12, bookId: 21 },
  'Song of Solomon': { title: 'Песнь Песней', chapters: 8, bookId: 22 },
  Isaiah: { title: 'Исаия', chapters: 66, bookId: 23 },
  Jeremiah: { title: 'Иеремия', chapters: 52, bookId: 24 },
  Lamentations: { title: 'Плач Иеремии', chapters: 5, bookId: 25 },
  Ezekiel: { title: 'Иезекииль', chapters: 48, bookId: 26 },
  Daniel: { title: 'Даниил', chapters: 12, bookId: 27 },
  Hosea: { title: 'Осия', chapters: 14, bookId: 28 },
  Joel: { title: 'Иоиль', chapters: 3, bookId: 29 },
  Amos: { title: 'Амос', chapters: 9, bookId: 30 },
  Obadiah: { title: 'Авдий', chapters: 1, bookId: 31 },
  Jonah: { title: 'Иона', chapters: 4, bookId: 32 },
  Micah: { title: 'Михей', chapters: 7, bookId: 33 },
  Nahum: { title: 'Наум', chapters: 3, bookId: 34 },
  Habakkuk: { title: 'Аввакум', chapters: 3, bookId: 35 },
  Zephaniah: { title: 'Софония', chapters: 3, bookId: 36 },
  Haggai: { title: 'Аггей', chapters: 2, bookId: 37 },
  Zechariah: { title: 'Захария', chapters: 14, bookId: 38 },
  Malachi: { title: 'Малахия', chapters: 4, bookId: 39 },
};

export const NewTestament = {
  Matthew: { title: 'Матфея', chapters: 28, bookId: 40 },
  Mark: { title: 'Марка', chapters: 16, bookId: 41 },
  Luke: { title: 'Луки', chapters: 24, bookId: 42 },
  John: { title: 'Иоанна', chapters: 21, bookId: 43 },
  Acts: { title: 'Деяния', chapters: 28, bookId: 44 },
  Romans: { title: 'Римлянам', chapters: 16, bookId: 45 },
  '1 Corinthians': { title: '1 Коринфянам', chapters: 16, bookId: 46 },
  '2 Corinthians': { title: '2 Коринфянам', chapters: 13, bookId: 47 },
  Galatians: { title: 'Галатам', chapters: 6, bookId: 48 },
  Ephesians: { title: 'Ефесянам', chapters: 6, bookId: 49 },
  Philippians: { title: 'Филиппийцам', chapters: 4, bookId: 50 },
  Colossians: { title: 'Колоссянам', chapters: 4, bookId: 51 },
  '1 Thessalonians': { title: '1 Фессалоникийцам', chapters: 5, bookId: 52 },
  '2 Thessalonians': { title: '2 Фессалоникийцам', chapters: 3, bookId: 53 },
  '1 Timothy': { title: '1 Тимофею', chapters: 6, bookId: 54 },
  '2 Timothy': { title: '2 Тимофею', chapters: 4, bookId: 55 },
  Titus: { title: 'Титу', chapters: 3, bookId: 56 },
  Philemon: { title: 'Филимону', chapters: 1, bookId: 57 },
  Hebrews: { title: 'Евреям', chapters: 13, bookId: 58 },
  James: { title: 'Иакова', chapters: 5, bookId: 59 },
  '1 Peter': { title: '1 Петра', chapters: 5, bookId: 60 },
  '2 Peter': { title: '2 Петра', chapters: 3, bookId: 61 },
  '1 John': { title: '1 Иоанна', chapters: 5, bookId: 62 },
  '2 John': { title: '2 Иоанна', chapters: 1, bookId: 63 },
  '3 John': { title: '3 Иоанна', chapters: 1, bookId: 64 },
  Jude: { title: 'Иуда', chapters: 1, bookId: 65 },
  Revelation: { title: 'Откровение', chapters: 22, bookId: 66 },
};

export const ALL_BOOKS = { ...OldTestament, ...NewTestament };