// bibleData.ts

export const OldTestament = {
  Genesis: { title: 'Бытие', chapters: 50 },
  Exodus: { title: 'Исход', chapters: 40 },
  Leviticus: { title: 'Левит', chapters: 27 },
  Numbers: { title: 'Числа', chapters: 36 },
  Deuteronomy: { title: 'Второзаконие', chapters: 34 },
  Joshua: { title: 'Иисус Навин', chapters: 24 },
  Judges: { title: 'Судей', chapters: 21 },
  Ruth: { title: 'Руфь', chapters: 4 },
  '1 Samuel': { title: '1 Царств', chapters: 31 },
  '2 Samuel': { title: '2 Царств', chapters: 24 },
  '1 Kings': { title: '3 Царств', chapters: 22 },
  '2 Kings': { title: '4 Царств', chapters: 25 },
  '1 Chronicles': { title: '1 Паралипоменон', chapters: 29 },
  '2 Chronicles': { title: '2 Паралипоменон', chapters: 36 },
  Ezra: { title: 'Ездра', chapters: 10 },
  Nehemiah: { title: 'Неемия', chapters: 13 },
  Esther: { title: 'Есфирь', chapters: 10 },
  Job: { title: 'Иов', chapters: 42 },
  Psalms: { title: 'Псалтирь', chapters: 150 },
  Proverbs: { title: 'Притчи', chapters: 31 },
  Ecclesiastes: { title: 'Екклесиаст', chapters: 12 },
  'Song of Solomon': { title: 'Песнь Песней', chapters: 8 },
  Isaiah: { title: 'Исаия', chapters: 66 },
  Jeremiah: { title: 'Иеремия', chapters: 52 },
  Lamentations: { title: 'Плач Иеремии', chapters: 5 },
  Ezekiel: { title: 'Иезекииль', chapters: 48 },
  Daniel: { title: 'Даниил', chapters: 12 },
  Hosea: { title: 'Осия', chapters: 14 },
  Joel: { title: 'Иоиль', chapters: 3 },
  Amos: { title: 'Амос', chapters: 9 },
  Obadiah: { title: 'Авдий', chapters: 1 },
  Jonah: { title: 'Иона', chapters: 4 },
  Micah: { title: 'Михей', chapters: 7 },
  Nahum: { title: 'Наум', chapters: 3 },
  Habakkuk: { title: 'Аввакум', chapters: 3 },
  Zephaniah: { title: 'Софония', chapters: 3 },
  Haggai: { title: 'Аггей', chapters: 2 },
  Zechariah: { title: 'Захария', chapters: 14 },
  Malachi: { title: 'Малахия', chapters: 4 },
};

export const NewTestament = {
  Matthew: { title: 'Матфея', chapters: 28 },
  Mark: { title: 'Марка', chapters: 16 },
  Luke: { title: 'Луки', chapters: 24 },
  John: { title: 'Иоанна', chapters: 21 },
  Acts: { title: 'Деяния', chapters: 28 },
  Romans: { title: 'Римлянам', chapters: 16 },
  '1 Corinthians': { title: '1 Коринфянам', chapters: 16 },
  '2 Corinthians': { title: '2 Коринфянам', chapters: 13 },
  Galatians: { title: 'Галатам', chapters: 6 },
  Ephesians: { title: 'Ефесянам', chapters: 6 },
  Philippians: { title: 'Филиппийцам', chapters: 4 },
  Colossians: { title: 'Колоссянам', chapters: 4 },
  '1 Thessalonians': { title: '1 Фессалоникийцам', chapters: 5 },
  '2 Thessalonians': { title: '2 Фессалоникийцам', chapters: 3 },
  '1 Timothy': { title: '1 Тимофею', chapters: 6 },
  '2 Timothy': { title: '2 Тимофею', chapters: 4 },
  Titus: { title: 'Титу', chapters: 3 },
  Philemon: { title: 'Филимону', chapters: 1 },
  Hebrews: { title: 'Евреям', chapters: 13 },
  James: { title: 'Иакова', chapters: 5 },
  '1 Peter': { title: '1 Петра', chapters: 5 },
  '2 Peter': { title: '2 Петра', chapters: 3 },
  '1 John': { title: '1 Иоанна', chapters: 5 },
  '2 John': { title: '2 Иоанна', chapters: 1 },
  '3 John': { title: '3 Иоанна', chapters: 1 },
  Jude: { title: 'Иуда', chapters: 1 },
  Revelation: { title: 'Откровение', chapters: 22 },
};

export const ALL_BOOKS = { ...OldTestament, ...NewTestament };